### ISSUE TITLE
Issue with the erosion solver(I think it is the erosion image)

### ISSUE THREAD

**Issue by joelRVC** [ozikazina/Hydra#12]
Hi. First of all I want to thank you for creating this, it looks very interesting. I tried it with a mountain model and when the geonodes preview appears, certain parts of geometry jump to infinite locations. I thought it was because of my model so I tried with Suzanne but I get similar behavior, I looked for the image generated by the erosion and in both scenarios it has certain pixels with errors.

I tried with blender 4.3 beta and also with 4.0, in the latter I show the image generated by the erosion:

Blender 4.3b:

https://github.com/user-attachments/assets/ce16a1c3-35e9-4612-84b3-8a70fb540959

Blender 4.0.2:

https://github.com/user-attachments/assets/41a1f346-4367-484a-b89e-61587804c90c

![{B6EF1716-D05B-4535-9C49-66712A1339FD}](https://github.com/user-attachments/assets/b041dfce-6243-4ef5-8a1b-996b41d05825)

**Comment by ozikazina** [comment]
Hello. The latest release doesn't yet support overlapping geometry (planets, Susanne and so on), but I've never seen it fail like that. What GPU do you have and what operating system are you using?

I'll try it with the release version tommorow, it's possible I fixed the issue since then:
![obrazek](https://github.com/user-attachments/assets/40c269eb-9fb7-41fe-ad8f-2138feeeb2e7)

**Comment by joelRVC** [comment]
Thanks for the response. I have an Intel UHD 620 integrated GPU and a Radeon RX 560 discrete GPU.

> I'll try it with the release version tommorow, it's possible I fixed the issue since then:

Thanks, I'll wait for that release then.

**Comment by ozikazina** [comment]
Could you please send a heightmap generated by the _Hydra - Heightmaps_ panel and a heightmap after thermal erosion? The heightmap for susanne seems to generate correctly on your machine but then something goes very wrong during erosion.

**Comment by joelRVC** [comment]
I'll share an example with the mountain I mentioned before. It seems that the heighmap is generated without problems.

![{0C99583A-0F29-41B4-8EFC-CCBE963CAF74}](https://github.com/user-attachments/assets/55a75025-0423-4c7a-98c9-3aa3b216bd45)

With the heightmap after erosion, do you mean the image called displacement?

![{7E0C6883-EA20-4579-8F81-24A55AD80899}](https://github.com/user-attachments/assets/cc30e833-13b6-475e-8a2e-78f9cfec1a8e)

**Comment by ozikazina** [comment]
I meant the heightmap result - you can export it using the image button in the _Result_ section (next to the geometry nodes symbol).

My only guess right now is that the erosion shaders launch too many threads for older GPUs. Check the console after launch for any errors, but if it runs, then the shaders probably compile fine. I'll try to send you a development version next week with modified shaders.

**Comment by ozikazina** [comment]
Here is a modified version of Hydra: 
[Hydra_1.2.0dev.zip](https://github.com/user-attachments/files/17354711/Hydra_1.2.0dev.zip)
It has a panel in 3D View which will launch some tests to check how your system behaves. It creates two images and also prints OpenGL info in the console.
I've added some memory barriers to thermal erosion and clamped the result, so it at least shouldn't explode to infinity. You could also try to run thermal erosion multiple times to see if it breaks in the exact same places.
![tabs](https://github.com/user-attachments/assets/7ec456fe-dfee-458c-8aae-4c5a4dfe5545)
![tests](https://github.com/user-attachments/assets/82b4429f-7d96-4318-8542-6f4766463168)

**Comment by joelRVC** [comment]
Hi. When I try to install this version in the addon menu a warning appears "there is no moderngl module", nor does the submenu where external dependencies could be installed. So I installed them manually but when I restart blender I get this notice in the console:

```
ModernGL not found.
Traceback (most recent call last):
  File "E:\RECURSOS Y software especializado\Blender\Blender versiones anteriores o experimentales\daily\blender-4.3.0\4.3\scripts\modules\addon_utils.py", line 407, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\RECURSOS Y software especializado\Blender\Blender versiones anteriores o experimentales\daily\blender-4.3.0\4.3\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\joels\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Hydra\__init__.py", line 43, in <module>
    from Hydra.addon.preferences import get_exports
  File "C:\Users\joels\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Hydra\addon\__init__.py", line 3, in <module>
    from Hydra.addon import preferences, properties, ops_heightmap, ops_common, ops_object, ops_image, ui_common, ui_image, ui_object, ui_nodes, ops_nodes
  File "C:\Users\joels\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Hydra\addon\ops_heightmap.py", line 6, in <module>
    from Hydra import common
  File "C:\Users\joels\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Hydra\common.py", line 3, in <module>
    import moderngl as mgl
ModuleNotFoundError: No module named 'moderngl'
```
The hydra panel in the viewport does not appear.

**Comment by joelRVC** [comment]
> I meant the heightmap result - you can export it using the image button in the _Result_ section (next to the geometry nodes symbol).
> 
> My only guess right now is that the erosion shaders launch too many threads for older GPUs. Check the console after launch for any errors, but if it runs, then the shaders probably compile fine. I'll try to send you a development version next week with modified shaders.

Btw, I also got what you asked for(with release version 1.1.0). In this case it is a cone-shaped cylinder with subdivisions, the erosion map seems to come out fine so your assumption could be correct.

![{0BF4C414-AF39-41B8-8856-69ED95A089FB}](https://github.com/user-attachments/assets/305eeb04-c508-4061-9f47-e331baf34062)

**Comment by ozikazina** [comment]
Hello and thank you for the heightmap. If both the generated heightmap and the eroded heightmap seem correct then it might just be something during their subtraction. You can also try to generate a landscape from the image (Decouple button in the Image viewer Hydra panel, and then generate in the Landscape panel). There might still be some invalid values that are hard to see.

Here is a slightly corrected version of the addon (I messed up an UI element in the preferences, the previous version would throw an exception anyway, sorry):
[Hydra_v1.2.0dev1.zip](https://github.com/user-attachments/files/17381373/Hydra_v1.2.0dev1.zip)

As for the moderngl issue, you could try deleting everything with moderngl and glcontext in Blender's python packages (C:\Program Files\Blender Foundation\Blender X.X\X.X\python\lib\site-packages on Windows) and reinstall it if you haven't done so. I've personally had an issue where Blender was reaching for system python's packages too for some reason. I must admit that getting extra libraries into Blender is a little scuffed right now though.

**Comment by joelRVC** [comment]
An apology for the delay. I just tested the version you sent, although now I focused on running the tests you added to the panel. Since it is data, I don't know what the results mean, so I am attaching the images that were generated and the test file in which I ran the addon (download the .txt and change the extension to just .rar, then unzip).

![{A227AE7A-5817-4EA1-B1BB-EFB80DDA1AFC}](https://github.com/user-attachments/assets/0e33ee4d-7f1b-4d3f-8976-821a8cad3743)

[hydra test.rar.txt](https://github.com/user-attachments/files/17447619/hydra.test.rar.txt)

**Comment by ozikazina** [comment]
Thank you for the data. All individual shader functions seem to work fine and so do large thread blocks, so my idea was incorrect. I may have discovered a bug in moderngl with AMD and texture binding, but that doesn't come up in the erosion algorithms used. Here is a second set of tests (you only need to replace the file in the addon's root):
[hyd_tests.zip](https://github.com/user-attachments/files/17494353/hyd_tests.zip)

It mainly tests thermal erosion a bunch of times because so far it seems that the addon literaly just fails at subtracting two images.

**Comment by joelRVC** [comment]
![{AD87D5CE-98CB-474A-A679-FA2CFD644C7E}](https://github.com/user-attachments/assets/1202708b-cd0d-42b8-9452-f05787cd7ec4)
[textures.rar.txt](https://github.com/user-attachments/files/17532450/textures.rar.txt)

**Comment by ozikazina** [comment]
Thanks again.
I'm gonna be honest, I still have no idea what's going on. It seems now that there is some unwanted dependency between erosion runs when it's on your system. I wanted to write a proper suite of unit tests before, so it looks like I'm going to have to now if you don't mind running them 😅
I'll have to do it for every step of the pipeline, so writing them will take me some time.

**Comment by joelRVC** [comment]
Of course, I put my help at your disposal.

**Comment by ImagePlant** [comment]
I'm happy to help test as well if need be.  I'm running an Arc A770 gpu on
Win11.
